import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Custom favicon per environment",
  description: "Generated by create next app",
  icons: [
    {
      rel: "icon",
      url: process.env.NODE_ENV === "production" ? "./env-favicon.ico" : "./env-favicon-dev.ico",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
